networks:
  homelab:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.2
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    networks:
      - homelab
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /homelab/media/movies
        target: /Movies
        read_only: true
      - type: bind
        source: /homelab/media/shows
        target: /Shows
        read_only: true
      - type: bind
        source: /homelab/media/music
        target: /Music
        read_only: true
    restart: always
    environment:
      - TZ=Europe/Tallinn
    group_add:
      - "109"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
        #- /dev/dri/card0:/dev/dri/card0

