networks:
  homelab:
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - homelab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
    volumes:
      - ./config:/config
      - /homelab/media/shows:/shows
      - /homelab/downloads:/downloads
    ports:
      - 8098:8989
    restart: unless-stopped

