networks:
  homelab:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    networks:
      - homelab
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: /homelab/media/movies
        target: /Movies
        read_only: true
      - type: bind
        source: /homelab/media/shows
        target: /Shows
        read_only: true
      - type: bind
        source: /homelab/media/music
        target: /Music
        read_only: true
    restart: always
    environment:
      - TZ=Europe/Tallinn
    group_add:
      - "109"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
        #- /dev/dri/card0:/dev/dri/card0

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - homelab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
    volumes:
      - ./sonarr/config:/config
      - /homelab/media/shows:/shows
      - /homelab/downloads:/downloads
    ports:
      - 8098:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - homelab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
    volumes:
      - ./radarr/config:/config
      - /homelab/media/movies:/movies
      - /homelab/downloads:/downloads
    ports:
      - 8097:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - homelab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 8099:9696
    restart: unless-stopped

      #jellyseerr:
    #image: fallenbagel/jellyseerr:latest
    #container_name: jellyseerr
    #networks:
    #  - homelab
    #environment:
    #  - LOG_LEVEL=debug
    #  - TZ=Europe/Tallinn
    #ports:
    #  - 8100:5055
    #volumes:
    #  - ./jellyseerr/config:/app/config
    #restart: unless-stopped

