services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: host
    # This makes IPv6 easier; see below
    restart: always
    # Restart the updater after reboot
    user: "${PUID}:${PGID}"
    # Run the updater with specific user/group IDs
    cap_drop:
      - all
      # Drop all other capabilities
    read_only: true
    # Make the container filesystem read-only
    security_opt:
      # Another protection to restrict superuser privileges
      - no-new-privileges:true
    env_file:
      - .env
