- name: Setup blog
  hosts: blog

  tasks:
    - name: Close app if running
      community.docker.docker_compose_v2:
        project_src: ~/blog/
        state: absent

    - name: Add necessary files for the app
      synchronize:
        src: ../blog
        dest: ~/

    - name: Start the app
      community.docker.docker_compose_v2:
        project_src: ~/blog/
        state: present # This can be 'started', 'stopped', 'restarted', 'absent'
        build: always # Optional: Set to yes if you want to build images
